# Generates blacklists for Blacklists.js.

library(AnnotationHub)
ahub <- AnnotationHub()
tag <- c(
    "AH95775", # Ensembl mouse v104
    "AH95744", # Ensembl human v104
    "AH95683"  # Ensembl C. elegans v104
)

blacklists <- list(
    mito = list(ensembl = character(0), symbol = character(0)),
    ribo = list(ensembl = character(0), symbol = character(0)),
    vdj = list(ensembl = character(0), symbol = character(0))
);

for (e in tag) {
    ens <- ahub[[e]]
    info <- select(ens, keys=keys(ens), keytype="GENEID", columns=c("GENEID", "SYMBOL", "SEQNAME", "GENEBIOTYPE"))

    is.mito <- info$SEQNAME %in% c("MT", "M", "chrM", "chrMT", "MtDNA")
    blacklists$mito$ensembl <- c(blacklists$mito$ensembl, info$GENEID[is.mito])
    blacklists$mito$symbol <- c(blacklists$mito$symbol, info$SYMBOL[is.mito])

    is.ribo <- grepl("^Rp[ls][0-9]", info$SYMBOL, ignore.case=TRUE) 
    blacklists$ribo$ensembl <- c(blacklists$ribo$ensembl, info$GENEID[is.ribo])
    blacklists$ribo$symbol <- c(blacklists$ribo$symbol, info$SYMBOL[is.ribo])

    is.vdj <- grepl("^TR_", info$GENEBIOTYPE) | grepl("^IG_", info$GENEBIOTYPE)
    blacklists$vdj$ensembl <- c(blacklists$vdj$ensembl, info$GENEID[is.vdj])
    blacklists$vdj$symbol <- c(blacklists$vdj$symbol, info$SYMBOL[is.vdj])
}

dir.create("blacklists")
for (x in names(blacklists)) {
    fname <- file.path("blacklists", paste0(x, ".js"))
    write("/* DO NOT EDIT THIS FILE! Modify blacklists.js.R instead. */\n", file=fname)
    write(sprintf("var %s = {};", x), file=fname, append=TRUE)
    write(sprintf("%s.ensembl = new Set([%s]);", x, paste(sprintf("\"%s\"", blacklists[[x]]$ensembl), collapse=",")), file=fname, append=TRUE)
    write(sprintf("%s.symbol = new Set([%s]);", x, paste(sprintf("\"%s\"", blacklists[[x]]$symbol), collapse=",")), file=fname, append=TRUE)
}
