on:
  push:
    branches:
      - master

      
name: Build documentation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2

    - name: Restore the node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('**/package.json') }}

    - name: Install JSDoc
      run: npm i --include-dev

    - name: Run JSDoc
      run: npm run jsdoc

    - name: GH Pages Deployment
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/built
        target-folder: docs
        clean: true # Automatically remove deleted files from the deploy branch
