on: [push]

name: Test JS bindings

jobs:
  # Building the RDS files for the various RDS-reading utilities.
  build_rds:
    runs-on: ubuntu-latest
    container: rocker/r-base:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build RDS files
      run: |
        cd tests/rds
        R -f generate.R

    - name: Upload RDS files
      uses: actions/upload-artifact@v3
      with:
        name: rds-files
        path: tests/rds/*.rds

  check:
    runs-on: ubuntu-latest
    needs: build_rds
    container: ghcr.io/kanaverse/scran.js/builder:latest
    defaults:
      run:
        working-directory: /scran.js

    steps:
    - name: Check emsdk version
      run: |
        emsdk install 3.1.43

    - name: Get to the right branch
      run: |
        git fetch --all
        git checkout $GITHUB_SHA

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Update node build 
      run: bash build.sh main

    - name: Update NPM packages
      run: npm i --include=dev

    - name: Download RDS files
      uses: actions/download-artifact@v3
      with:
        name: rds-files
        path: /scran.js/tests/rds

    - name: Run tests
      run: |
        export CHECK_RDS=1
        npm run test
